//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calificacione
    {
        public int IdCal { get; set; }
        public string IdEstudiante { get; set; }
        public string IdProfesor { get; set; }
        public double Valor { get; set; }
        public string Alpha { get; set; }
        public string ClaveAsignatura { get; set; }
    }
}
