//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Database1Entities : DbContext
    {
        public Database1Entities()
            : base("name=Database1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Autenticacion> Autenticacions { get; set; }
        public virtual DbSet<Asignatura> Asignaturas { get; set; }
        public virtual DbSet<Calificacione> Calificaciones { get; set; }
        public virtual DbSet<Profesore> Profesores { get; set; }
        public virtual DbSet<ListCalEst> ListCalEsts { get; set; }
        public virtual DbSet<Estudiante> Estudiantes { get; set; }
    
        public virtual ObjectResult<GetStudent_Result> GetStudent(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetStudent_Result>("GetStudent", idParameter);
        }
    
        public virtual ObjectResult<ListarCalsEst_Result> ListarCalsEst(string idEst)
        {
            var idEstParameter = idEst != null ?
                new ObjectParameter("IdEst", idEst) :
                new ObjectParameter("IdEst", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListarCalsEst_Result>("ListarCalsEst", idEstParameter);
        }
    
        public virtual ObjectResult<Autenticacion> GetAutenticacionById(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Autenticacion>("GetAutenticacionById", idParameter);
        }
    
        public virtual ObjectResult<Autenticacion> GetAutenticacionById(string id, MergeOption mergeOption)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Autenticacion>("GetAutenticacionById", mergeOption, idParameter);
        }
    }
}
